{{- if and .Values.celeryWorker.enabled .Values.celeryWorker.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "fury-api.fullname" . }}-celery-worker
  labels:
    {{- include "fury-api.labels" . | nindent 4 }}
    app.kubernetes.io/component: celery-worker
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "fury-api.fullname" . }}-celery-worker
  minReplicas: {{ .Values.celeryWorker.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.celeryWorker.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.celeryWorker.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.celeryWorker.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.celeryWorker.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.celeryWorker.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
